language:
  - python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pep8
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - pep8 example/example.py
  - pep8 example/test.py
  - py.test -vv example/test.py --cov example
  - coveralls

notifications:
  email: false
