language:
  - python

python:
  - 2.7

install:
  - pip install pytest-cov
  - pip install python-coveralls

script:
  - py.test -vv example/test.py --cov example
  - coveralls

notifications:
  email: false
